#!/bin/bash
REMOTE_HOST="zerocost.dev"
REMOTE_USER="www"
REMOTE_PATH="/home/www/breakscheduler"

sshcmd() {
    ssh ${REMOTE_USER}@${REMOTE_HOST} "$@"
}

sshcmd "cd $REMOTE_PATH && git pull origin master"

if [ "$1" == "--build" ]; then
    sshcmd "cd $REMOTE_PATH && . /home/www/.nvm/nvm.sh 10 && npm run build"
fi

